name: Python Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  matrix:
    python-version: ["3.10"]

jobs:
  Pep8:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Pep8
        run: |
          # stop the build if there are Python syntax errors or undefined names. The is 127 chars wide
          pycodestyle api/. --count --show-source --max-line-length=127 --statistics

  Pylint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pylint
        run: |
          pylint api/. --rcfile=.github/workflows/vanilla.rc
